name: CI

on:
  push:
    branches:
      - Combined
  pull_request:
    branches:
      - Combined
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.0.1

  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.0.app && /usr/bin/xcodebuild -version
      - name: run tests
        run: | 
          xcodebuild test -project SwiftUiTemplate.xcodeproj -scheme SwiftUITemplateDev -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.0' -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}
          
  SwiftFormat:
    runs-on: macos-latest
    steps:
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: xcode-latest
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run:
          xcodebuild test -project SwiftUITemplate.xcodeproj -scheme SwiftUITemplateDev -destination 'platform=iOS Simulator,name=iPhone 11,OS=16.2' -enableCodeCoverage YES -sdk macosx clean build
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: MD_APPLE_SDK_ROOT,RUNNER_OS,RUNNER_ARCH
